// Builds the "Aree di Intervento" maps from Natural Earth data (world-atlas),
// so coastlines and borders are real geography instead of a generated picture.
//
// Input:  scripts/map-points.json  (maps with extent, highlighted countries, pins)
// Output: public/img/<map.file>     (one static SVG per map, no runtime JS)
//         js/data/map-pins.js       (pin positions as % of each map box)
//
// Run with: npm run build:map

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoMercator, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(readFileSync(resolve(root, 'scripts/map-points.json'), 'utf8'));
// Natural Earth at 1:110m for the continental overview, 1:50m where coastlines are seen up close.
const atlas = {};
for (const resolution of ['110m', '50m']) {
  const world = JSON.parse(readFileSync(resolve(root, `node_modules/world-atlas/countries-${resolution}.json`), 'utf8'));
  atlas[resolution] = feature(world, world.objects.countries).features;
}
const countries = atlas['50m'];
const highlighted = new Set(config.highlight);

const names = new Set(countries.map((c) => c.properties.name));
const unknown = [...highlighted].filter((name) => !names.has(name));
if (unknown.length) throw new Error(`Countries not in world-atlas (check spelling): ${unknown.join(', ')}`);

function buildMap(map) {
  const { width: W, height: H } = map;
  const [[west, south], [east, north]] = map.extent;

  // Fit the lon/lat box to the canvas, then clip everything outside it.
  const corners = {
    type: 'MultiPoint',
    coordinates: [[west, south], [east, north], [west, north], [east, south]],
  };
  const projection = geoMercator().fitExtent([[0, 0], [W, H]], corners).clipExtent([[0, 0], [W, H]]);
  const path = geoPath(projection).digits(1);

  const base = [];
  const active = [];
  for (const country of atlas[map.resolution]) {
    const d = path(country);
    if (!d) continue;
    const name = country.properties.name;
    if (highlighted.has(name)) active.push(`<path d="${d}"><title>${name}</title></path>`);
    else base.push(`<path d="${d}"/>`);
  }

  const seaLabels = map.seaLabels.map(({ label, lon, lat, size = 13 }) => {
    const [x, y] = projection([lon, lat]);
    return `<text x="${x.toFixed(1)}" y="${y.toFixed(1)}" font-size="${size}">${label}</text>`;
  });

  // Dashed outline of any detail map drawn on top of this one (Mercator keeps it a rectangle).
  const frames = (map.frames || []).map((id) => {
    const [[fw, fs], [fe, fn]] = config.maps.find((m) => m.id === id).extent;
    const [x0, y0] = projection([fw, fn]);
    const [x1, y1] = projection([fe, fs]);
    return `<rect x="${x0.toFixed(1)}" y="${y0.toFixed(1)}" width="${(x1 - x0).toFixed(1)}" height="${(y1 - y0).toFixed(1)}"/>`;
  });

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${config.ariaLabel}">
<rect width="${W}" height="${H}" fill="#e8eff6"/>
<g fill="#d3dae3" stroke="#f8f9fa" stroke-width="0.6" stroke-linejoin="round">${base.join('')}</g>
<g fill="#1a4d80" stroke="#f8f9fa" stroke-width="0.8" stroke-linejoin="round">${active.join('')}</g>
<g fill="none" stroke="#1d5fb8" stroke-width="1.5" stroke-dasharray="5 4">${frames.join('')}</g>
<g fill="#6b8bab" font-family="Inter, sans-serif" font-style="italic" letter-spacing="0.08em" text-anchor="middle">${seaLabels.join('')}</g>
</svg>
`;
  writeFileSync(resolve(root, 'public/img', map.file), svg);
  console.log(`${map.file}: ${W}x${H}, ${active.length} highlighted of ${base.length + active.length} countries, ${(Buffer.byteLength(svg) / 1024).toFixed(1)} KB`);

  // Percent position of every pin that falls inside this map.
  const positions = {};
  for (const pin of config.pins) {
    const [x, y] = projection([pin.lon, pin.lat]);
    if (x < 0 || x > W || y < 0 || y > H) continue;
    positions[pin.id] = { x: +((x / W) * 100).toFixed(2), y: +((y / H) * 100).toFixed(2) };
  }
  return positions;
}

mkdirSync(resolve(root, 'public/img'), { recursive: true });
mkdirSync(resolve(root, 'js/data'), { recursive: true });

const positionsByMap = Object.fromEntries(config.maps.map((map) => [map.id, buildMap(map)]));

const pins = config.pins.map(({ lon, lat, ...pin }) => {
  const pos = {};
  for (const [mapId, positions] of Object.entries(positionsByMap)) {
    if (positions[pin.id]) pos[mapId] = positions[pin.id];
  }
  if (!pos.overview) throw new Error(`Pin outside the overview map: ${pin.id}`);
  return { ...pin, pos };
});

writeFileSync(
  resolve(root, 'js/data/map-pins.js'),
  `// Generated by scripts/build-map.mjs from scripts/map-points.json. Do not edit by hand.\nexport const MAP_PINS = ${JSON.stringify(pins, null, 2)};\n`,
);
console.log(`pins: ${pins.length}`);
